@startuml

skinparam ParticipantPadding 10
skinparam BoxPadding 5

actor User

box "Head"
participant Chat
participant QiChatbot
endbox

box "Tablet"
participant DialogflowChatbot
participant DialogflowAgent
participant StandardReplyReaction
participant DialogflowChatbotReaction
participant Say
endbox

box "Internet"
participant Dialogflow
endbox

User -> Chat: "Who are you ?"

activate Chat
Chat -> QiChatbot:  replyTo("Who are you ?")
activate QiChatbot
Chat -> DialogflowChatbot: replyTo("Who are you ?")

note left of QiChatbot: The QiChatbot has no rule\nin its topic that \ncorresponds to this\nuser utterance

activate DialogflowChatbot
DialogflowChatbot -> DialogflowAgent : answerTo("Who are you ?")
activate DialogflowAgent
DialogflowAgent ->> Dialogflow : send an asynchronous query containing "Who are you ?" to the online agent
activate Dialogflow
Chat <-- QiChatbot: return StandardReplyReaction(ChatbotReaction, FALLBACK))

deactivate QiChatbot
DialogflowAgent <-- Dialogflow : return an AIResponse containing "I'm Pepper the robot !"
deactivate Dialogflow
DialogflowChatbot <-- DialogflowAgent : return the AIReponse
deactivate DialogflowAgent

create DialogflowChatbotReaction
DialogflowChatbot -> DialogflowChatbotReaction : create a DialogflowChatbotReaction with "I'm Pepper the robot !"
create StandardReplyReaction
DialogflowChatbot -> StandardReplyReaction : create a ReplyReaction with (ChatbotReaction + priority)

deactivate QiChatbot
Chat <-- DialogflowChatbot: return StandardReplyReaction(DialogflowChatbotReaction, NORMAL))
deactivate DialogflowChatbot

activate Chat
note right of Chat: Choose the first NORMAL reaction if any
Chat -> DialogflowChatbotReaction: runWith(SpeechEngine)
deactivate Chat

activate DialogflowChatbotReaction
create Say
DialogflowChatbotReaction -> Say: SayBuilder.with(speechEngine).build()
DialogflowChatbotReaction ->> Say: async().run()
activate Say
Say -> User : "I'm Pepper the robot !"

DialogflowChatbotReaction -> Say: get() on the enclosing Future
Say --> DialogflowChatbotReaction

deactivate Say
DialogflowChatbotReaction --> Chat
deactivate DialogflowChatbotReaction
deactivate Chat

@enduml